name: maven
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [8, 9, 11, 17, 18]
        # and run on both Linux and Windows
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: github.ref != 'refs/heads/gh-pages'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - name: Build with Maven
        if: matrix.java != 8
        run: |
          mvn clean install -f pom.xml
      - name: Build with Maven w/o ecj
        if: matrix.java == 8
        run: |
          mvn clean install -f pom.xml -pl !ecj
      - name: Upload api artifact
        uses: actions/upload-artifact@v2
        if: matrix.java == 8 && matrix.os == 'ubuntu-latest'
        with:
          name: javayield-jar-artifact
          path: api/target/javayield-api-*.jar
      - name: Upload ecj artifact
        uses: actions/upload-artifact@v2
        if: matrix.java == 9 && matrix.os == 'ubuntu-latest'
        with:
          name: javayield-jar-artifact
          path: ecj/target/javayield-ecj-*.jar
      - name: Upload javac artifact
        uses: actions/upload-artifact@v2
        if: matrix.java == 8 && matrix.os == 'ubuntu-latest'
        with:
          name: javayield-jar-artifact
          path: javac/target/javayield-javac-*.jar
      - name: Upload runtime artifact
        uses: actions/upload-artifact@v2
        if: matrix.java == 8 && matrix.os == 'ubuntu-latest'
        with:
          name: javayield-jar-artifact
          path: runtime/target/javayield-runtime-*.jar
      - name: Upload transform artifact
        uses: actions/upload-artifact@v2
        if: matrix.java == 8 && matrix.os == 'ubuntu-latest'
        with:
          name: javayield-jar-artifact
          path: transform/target/javayield-transform-*.jar
